# yaml-language-server: $schema=https://json-schema.axonivy.com/app/12.0.0/variables.json
Variables:
  caseProcessViewer:
    passedColor: purple
    activeColor: rgba(59, 130, 246, 0.25)
    frequencyColor: green
    frequencyTextColor: black
